matrix:
  include:
  - os: osx
    osx_image: xcode10.2
    language: node_js
    node_js: '10'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    services: docker
    language: generic
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script:
- |
  ENVS=`env | grep -iE '^(DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_)([A-Z]|_)*=' | sed -n '/^[^\t]/s/=.*//p' | sed '/^$/d' | sed 's/^/-e /g' | tr '\n' ' '`
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    docker run $ENVS --rm \
      -v ${PWD}:/project \
      -v ~/.cache/electron:/root/.cache/electron \
      -v ~/.cache/electron-builder:/root/.cache/electron-builder \
      electronuserland/builder:wine \
      /bin/bash -c "npm ci && npm run dist:win"
  else
    npm run dist
  fi
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: CggPgXoP1nPQ0A3B8ZTtlZBFU2a/jgP6pLu/iaa2+EqWLU7nIMUN17IfOPCOfrw/2kuKtZOCQNgLh9Xrb3EOkS92QHOKuwsrmmPzuk02vQ0QgbhzmxSsbooUtVD9T2/bwJo5/eaNOG2RxpKmowFvjl97lrgO0xaD35qq1pvWElQYGKZpIopRj14XS4AjBu8UzWDvUZD1wX/NAnjhvB54NMg3Y9JJcWRPV2uiNmfqCR6riEmhA3xwqa4WmbMnjNl7olSEkG6U5Hya3g4wg8cAUqOrLTB7SPE0DHi+WrnDwTP+qKskqknzltfXEjk6Jkqego5f3ZnZJCJPuIddfQUnVLMvjIg6dYD82arhFfWoPg6Ub8hY1DWJEl3gFrnh/pwq+AkF2OYka/llr7+7d/P1iLPqSjP+eOGkO/BQcJWCz4GAMCt/h0T/QGB9VPBPBbAfIu/9L4zivLoXCHfD43UsdKKQJtrx7YViQmF1w1gPSeOi672/HbXk2C/+QDNTiD63UItiMOq8uZcKP268ZZgfZVzpKVZiJ5/1r69SRW+7wiJWNzI6B6vQWZRFJOGMyyuPX3U2eXT8jKQ7x3T2vk673kSXkLPNebr6hq3jOD/EHJVkZi/jw6fC0veEVttuFiYfueKcqyTBzaSvHAgRq6R28qxqPCyhmc6Eb5TKFfCljiQ=
  file:
    - dist/*.exe
    - dist/*.dmg
  on:
    tags: true
